config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
}

  namespace :admin do
    root to: "homes#top"
    get 'homes/about' => 'homes#about'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  scope module: :public do
    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :products, only: [:index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :reserve, only: [:new]
    post 'reserve/complete' => 'reserve#complete'
    post 'reserve/confirm' => 'reserve#confirm'# 確認画面
    post 'reserve/back' => 'reserve#back'# 確認画面から「入力画面に戻る」をクリックしたとき
    get "search" => "searches#search"
 end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
  
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div>
  <about-head>
   <div class="abhaikei">

    <h1>譲り合いで輝ける未来へ</h1>
    <h2>あなたの不要になった物は、誰かにとって特別なモノ。</h2>
    <h2>使わなくなった物には、まだ輝ける未来が待っています。</h2>
    <h2>warasiibeは人と人をつなぎ、モノに新たな活躍の場を提供するプラットフォームです。</h2>
    <h2>お世話になった感謝のしるしとして、次のステージを贈りましょう。</h2>
    <h2>断捨離は終わり、譲り合いは始まり。</h2>

        <%= link_to " さっそく始める", new_customer_registration_path, class: "btn-80" %>

   </div>
  </about-head>

  <about-body>
    <div class="container">
        <h1 class="tokucho">
          warasiibeの特徴
        </h1>
    </div>

    <div class="row">

      <div class="col-xs-6 col-lg-4">
          <div class="aboutcard-body">
            <h5 class="card-title">すべての商品が無料</h5>
            <p class="card-text">配送料のみの負担で欲しいものを譲り受けることができます。気軽に物々交換を楽しんでください。</p>

            <div class='tokucho-image'>
              <%= image_tag asset_path('about_car.jpg'), alt: "画像1", class:"image1" %>
            </div>

          </div>
      </div>

      <div class="col-xs-6 col-lg-4">
          <div class="aboutcard-body">
            <h5 class="card-title">面倒くさいやり取りは不要</h5>
            <p class="card-text">譲る方は(出品、着払いで配送)　受け取る方は(探す、気に入った商品に配送依頼を送る)の2ステップのみです。</p>

            <div class='tokucho-image'>
              <%= image_tag asset_path('about_people.jpg'), alt: "画像2", class:"image2" %>
            </div>

          </div>
      </div>

      <div class="col-xs-12 col-lg-4">
          <div class="aboutcard-body">
            <h5 class="card-title">サステナブルな未来づくり</h5>
            <p class="card-text">ワラシベ長者は持続可能な社会を目指し、大切な地球を守ることに貢献します。資源を使いまわすことはその一歩です。</p>

            <div class='tokucho-image'>
              <%= image_tag asset_path('about_heart.jpg'), alt: "画像3", class:"image3" %>
            </div>

          </div>
      </div>

    </div>
  </about-body>
</div>

app/views/homes/top.html.erb
<div class="haikei">
    <h1>モノの譲り合いで暮らしを豊かに</h1>
    <h2>あなたが使わなくなった物は、誰かにとって特別なモノ。</h2>
    <h2>まだまだ輝ける未来が待っています。</h2>
    <h2>お世話になった感謝のしるしとして、新たな旅路へ送り届けましょう。</h2>
    <h2>断捨離は終わり、譲り合いは始まり。</h2>


      <%= link_to " さっそく始める", new_customer_registration_path, class: "btn-80" %>

      <%= link_to "管理者の方はこちら", admin_session_path, class: "admin-button" %>


</div>