config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
}

  namespace :admin do
    root to: "homes#top"
    get 'homes/about' => 'homes#about'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  scope module: :public do
    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :products, only: [:index, :show, :create, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :notifications, only: [:index]
    resources :reserve, only: [:new]
    post 'reserve/complete' => 'reserve#complete'
    post 'reserve/confirm' => 'reserve#confirm'# 確認画面
    post 'reserve/back' => 'reserve#back'# 確認画面から「入力画面に戻る」をクリックしたとき
    get "search" => "searches#search"
 end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>Warasiibe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://kit.fontawesome.com/305c72cd32.js" crossorigin="anonymous"></script>

    <!--kaminari-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Kiwi+Maru&family=Merriweather+Sans:wght@500&family=Nunito&display=swap');
    </style>

  </head>

  <body>
    <% if admin_signed_in? %>
    
    <header>
      <%= link_to admin_products_path, class: 'headline' do %>
        waras<span>ii</span>be
      <% end %>

      <%= link_to admin_customers_path, class: 'button' do %>
        会員一覧
      <% end %>

      <%= link_to admin_products_path, class: 'button' do %>
        商品一覧
      <% end %>

      <%= link_to destroy_admin_session_path, method: :delete, class: 'button' do %>
        ログアウト
      <% end %>
    </header>

    <% elsif customer_signed_in? %>
    
    <header>
      <%= link_to public_customer_path(current_customer), class: 'headline' do %>
        waras<span>ii</span>be
      <% end %>

      <%= link_to public_notifications_path, class: 'button' do %>
        通知一覧
      <% end %>

      <%= link_to public_products_path, class: 'button' do %>
        商品を探す
      <% end %>

      <%= link_to destroy_customer_session_path, method: :delete, class: 'button' do %>
        ログアウト
      <% end %>
    </header>
    
    <% else %>
    
    <header>
      <%= link_to root_path, class: 'headline' do %>
        waras<span>ii</span>be
      <% end %>

      <%= link_to homes_about_path, class: 'button' do %>
        About
      <% end %>

      <%= link_to new_customer_registration_path, class: 'button' do %>
        新規登録
      <% end %>

      <%= link_to new_customer_session_path, class: "button" do %>
        ログイン
      <% end %>
    </header>
    
    <% end %>

    <%= yield %>


    <footer class="footer">
    <p class="footer-text">© All rights reserved by warasiibe</p>
    </footer>

  </body>



</html>